"use client"

import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
  
export default function RootLayout( {children} ) {
  return (
    <html lang="en">
      <head>
       <meta name="viewport" content="width=device-width"/>
      </head>
      <body  className={` flexCenter min-h-[100vh]`}>
        <div className="md:mt-20 max-[600px]:w-full bg-blue-200 md:p-20">
           {children}
        </div>
        </body>
    </html>
  )
}
